name: Frends.Oracle.ExecuteQuery Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Oracle.ExecuteQuery/**'
  workflow_dispatch:
  

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: script
      run: |
        chmod +x ../build/deploy_oracle_docker_container.sh
      shell: bash
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Oracle.ExecuteQuery
      env_var_name_1: HiQ_OracleDb_connectionString
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}