name: Frends.Oracle.ExecuteQuery Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Oracle.ExecuteQuery/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Oracle.ExecuteQuery
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_ORACLEDB_CONNECTIONSTRING }}