name: Frends.Oracle.ExecuteQuery Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Oracle.ExecuteQuery/**'
  workflow_dispatch:


jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.Oracle.ExecuteQuery
      prebuild_command: chmod 777 ./_build/deploy_oracle_docker_container.sh && ./_build/deploy_oracle_docker_container.sh
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      
